---

name: Create issue on commit
 
on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - env: 
          GH_Token: "${{ secrets.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 }}"
        run: |
          curl --request POST \
          --url https://api.github.com/repos/HendrikBorgelt/Test_repositroy_for_Mathias_Gacka/issues \
          --header "authorization: Bearer ${{ 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 }}" \
          --header "content-type: application/json" \
          --data '{ "title": "Automated issue for commit: ${{ github.sha }}", "body": "This issue was automatically created by the GitHub Action workflow. \n\n The commit hash was: _${{ github.sha }}_." }' \
          --fail


        
